
To build docker images for tokay use the build script. If run without
options, all source is checked out from github (changes to the local
directory will not be included).  To build an 'experimental' image, 
add the -e option to the build script.  The source in the current working
directory will be used; 3rd party source will be fetched from github
during the build. 

The -x option can be given on the build.ksh command line to cause
the image to be exported to a .tar file in the local directory. 
